Setup with beacon
martide/literature pull request #1
Opened 2022-08-30 07:55 UTC by christianlj

2022-09-22 14:31 UTC, samhamilton requested changes

2022-09-22 14:31 UTC, samhamilton commented on lib/literature/migrations/post.ex
> +      add(:excerpt, :text)
please rename - perhaps to html or content?

2022-09-22 14:38 UTC, samhamilton commented on lib/literature/components/layout_component.ex
> +        &copy; <%= Date.utc_today().year %> <a href="https://martide.com/" class="hover:underline">Literature</a>. All Rights Reserved.
dont think we need this

2022-09-22 14:42 UTC, samhamilton commented on lib/literature/post.ex
> +    belongs_to(:primary_author, Author)
post should be able to have many authors and many tags

2022-09-22 14:46 UTC, samhamilton commented on lib/literature/uploader.ex
> +    {:convert, "-resize 10% -format webp", :webp}
please verify this makes the max width 100px and not 10% of the size of the original file

2022-09-22 14:48 UTC, samhamilton commented on priv/static/css/app.css
> +/*
can you find a way to include via the npm package so we remember to update them

2022-09-23 02:27 UTC, samhamilton commented on lib/literature/post.ex
> +    belongs_to(:primary_author, Author)
and lets rename to remove the "primary_" and go with authors and tags

2022-09-30 13:39 UTC, technicalcapt reviewed
@christianlj Code wise LGTM 👍 

I didn't test it. Let me know if we can test it from https://github.com/martide/elixir/pull/5988 🤔
(cc @samhamilton )

2022-10-03 05:12 UTC, merged